### ISSUE TITLE
Error al cargar por segunda vez los mismo datos en el mapa

### ISSUE THREAD

**Issue by luiscolungaperez** [conacyt-dai/dai-maps#30]
Este error se presenta al realizar los siguientes pasos:
1. Se selecciona un estado. 
2. Se selecciona otro estado diferente
3. Se vuelve a seleccionar el primer estado seleccionado

Esto hace que los polígonos se rompan y no aparezcan nuevamente en el mapa.

**Comment by andres-geotec** [comment]
Gracias @luiscolungaperez lo estamos revisando 👾

**Comment by andres-geotec** [comment]
Para este tipo de interacciones se recomienda el uso del formato GeoJSON.

Sin embargo, te dejamos un ejemplo de interacción con el formato TopoJSON en la documentación con el archivo [uso-basico/9-topojson-dinamico.vue](https://github.com/conacyt-dai/dai-maps/blob/fix/topojson-review-dinamic/docs/.vuepress/components/uso-basico/9-topojson-dinamico.vue)
